blank_issues_enabled: true
contact_links:
  - name: Discord Community Support
    url: https://androz2091.fr/discord
    about: Issue tracker is for bug reports and feature requests only. If you need help, go to Discussions or join our Discord server.
