name: Publish Latest
on:
  workflow_dispatch:
  release:
    types: [published]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  publish-npm:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-cache-node
      - run: yarn install --immutable
      - name: Build and publish
        run: yarn publish-packages
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.npm_token}}
          DP_PUBLISH_DEV: false
